# Generated by Django 5.1.5 on 2025-01-23 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rental", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="name",
            field=models.CharField(
                choices=[
                    ("Wing", "Wing Team"),
                    ("Fuselage", "Fuselage Team"),
                    ("Tail", "Tail Team"),
                    ("Avionics", "Avionics Team"),
                    ("Assembly", "Assembly Team"),
                    ("NoTeam", "No Team"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
    ]
