# Generated by Django 5.1.5 on 2025-01-24 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rental", "0002_alter_team_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assembly",
            name="aircraft",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="assemblies", to="rental.aircraft"
            ),
        ),
        migrations.AlterField(
            model_name="assembly",
            name="avionics",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assembled_avionics",
                to="rental.part",
            ),
        ),
        migrations.AlterField(
            model_name="assembly",
            name="fuselages",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assembled_fuselages",
                to="rental.part",
            ),
        ),
        migrations.AlterField(
            model_name="assembly",
            name="tails",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assembled_tails",
                to="rental.part",
            ),
        ),
        migrations.AlterField(
            model_name="assembly",
            name="wings",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assembled_wings",
                to="rental.part",
            ),
        ),
    ]
